main: com.firstplugin.App
name: Frogin
version: 0.03 Pre-release
description: The plugin Made by FrogMan!
api-version: 1.18
author: FrogMan#4369
website: https://github.com/Frogman03/Minecraft-Plugin-1

commands:
  credit:
    usuage: /<command>
    description: Shows the credits for this plugin.
    alias: fcreds