name: Frogin
version: 0.21 Pre-Release
main: me.froglin.frogin.Frogin
api-version: 1.18
authors: [ FrogMan ]
description: The Frog-Made plugin
website: https://github.com/Frogman03/Frogin
commands:
  god:
    description: Become Invincible.
    usage: /<command>

  version:
    description: shows the version of the plugin.
    usage: /<command>
    aliases: fver

  credit:
    description: Shows credit to the creators.
    usage: /<command>

  website:
    description: Shows the website of the github repo.
    usage: /<command>

  Adminhello:
    description: Says hello to an administrator
    usage: /<command>

  About:
    description: Says a little description of the plugin!
    usage: /<command>

  hm:
    description: says hm back.
    usage: /<command>

  fkill:
    description: Kills a player with the Frogin plugin.
    usage: /<command>

  setspawn:
    description: Sets the spawn
    usage: /<command>

  spawn:
    description: Teleports you to the spawn
    usage: /<command>

  fly:
    description: Allows the executor to fly if they have the permissions.
    usage: /<command>

  idk:
    description: IDK is suggested by mbs
    usage: /<command>

  vanish:
    description: makes you disappear
    usage: /<command>

  sb:
    description: Displays the scoreboard test.

  rtp:
    description: Teleports the player to a random location